const cartogram_data = [
  { jd: "ME", score_jd: 50, state: "ME", score_st: 5 },
  { jd: "NYN", score_jd: 67, state: "NY", score_st: 88 },
  { jd: "NYE", score_jd: 36, state: "NY", score_st: 88 },
  { jd: "VT", score_jd: 50, state: "VT", score_st: 10 },
  { jd: "NH", score_jd: 50, state: "NH", score_st: 15 },
  { jd: "WIW", score_jd: 50, state: "WI", score_st: 25 },
  { jd: "WIE", score_jd: 50, state: "WI", score_st: 25 },
  { jd: "MIW", score_jd: 50, state: "MI", score_st: 33 },
  { jd: "MIE", score_jd: 50, state: "MI", score_st: 22 },
  { jd: "NYW", score_jd: 45, state: "NY", score_st: 13 },
  { jd: "NYS", score_jd: 50, state: "NY", score_st: 50 },
  { jd: "MA", score_jd: 34, state: "MA", score_st: 50 },
  { jd: "WAW", score_jd: 50, state: "WA", score_st: 50 },
  { jd: "WAE", score_jd: 50, state: "WA", score_st: 50 },
  { jd: "ID", score_jd: 67, state: "ID", score_st: 44 },
  { jd: "MT", score_jd: 50, state: "MT", score_st: 50 },
  { jd: "ND", score_jd: 89, state: "ND", score_st: 23 },
  { jd: "MN", score_jd: 87, state: "MN", score_st: 50 },
  { jd: "ILN", score_jd: 50, state: "IL", score_st: 50 },
  { jd: "ILC", score_jd: 0, state: "IL", score_st: 88 },
  { jd: "INN", score_jd: 50, state: "IN", score_st: 60 },
  { jd: "OHN", score_jd: 14, state: "OH", score_st: 23 },
  { jd: "PAE", score_jd: 25, state: "PA", score_st: 50 },
  { jd: "PAW", score_jd: 50, state: "PA", score_st: 99 },
  { jd: "NJ", score_jd: 50, state: "NJ", score_st: 80 },
  { jd: "CT", score_jd: 36, state: "CT", score_st: 22 },
  { jd: "RI", score_jd: 50, state: "RI", score_st: 16 },
  { jd: "OR", score_jd: 47, state: "OR", score_st: 50 },
  { jd: "NV", score_jd: 58, state: "NV", score_st: 5 },
  { jd: "WY", score_jd: 50, state: "WY", score_st: 70 },
  { jd: "SD", score_jd: 50, state: "SD", score_st: 27 },
  { jd: "IAN", score_jd: 50, state: "IA", score_st: 38 },
  { jd: "IAS", score_jd: 50, state: "IA", score_st: 49 },
  { jd: "ILS", score_jd: 50, state: "IL", score_st: 50 },
  { jd: "INS", score_jd: 50, state: "IN", score_st: 32 },
  { jd: "OHS", score_jd: 50, state: "OH", score_st: 50 },
  { jd: "PAM", score_jd: 50, state: "PA", score_st: 50 },
  { jd: "VAW", score_jd: 50, state: "VA", score_st: 90 },
  { jd: "MD", score_jd: 50, state: "MD", score_st: 123 },
  { jd: "DC", score_jd: 50, state: "DC", score_st: 50 },
  { jd: "DE", score_jd: 50, state: "DE", score_st: 45 },
  { jd: "CAN", score_jd: 50, state: "CA", score_st: 50 },
  { jd: "UT", score_jd: 69, state: "UT", score_st: 34 },
  { jd: "CO", score_jd: 50, state: "CO", score_st: 45 },
  { jd: "OKE", score_jd: 70, state: "OK", score_st: 45 },
  { jd: "GAN", score_jd: 89, state: "GA", score_st: 45 },
  { jd: "NE", score_jd: 50, state: "NE", score_st: 56 },
  { jd: "MOW", score_jd: 50, state: "MO", score_st: 50 },
  { jd: "MOE", score_jd: 50, state: "MO", score_st: 5 },
  { jd: "KYW", score_jd: 80, state: "KY", score_st: 50 },
  { jd: "KYE", score_jd: 90, state: "KY", score_st: 78 },
  { jd: "WVN", score_jd: 123, state: "WV", score_st: 50 },
  { jd: "WVS", score_jd: 111, state: "WVS", score_st: 0 },
  { jd: "VAE", score_jd: 0, state: "VA", score_st: 50 },
  { jd: "CAC", score_jd: 100, state: "CA", score_st: 1 },
  { jd: "CAE", score_jd: 50, state: "CA", score_st: 50 },
  { jd: "AZ", score_jd: 33, state: "AZ", score_st: 50 },
  { jd: "NM", score_jd: 50, state: "NM", score_st: 50 },
  { jd: "KS", score_jd: 99, state: "KS", score_st: 44 },
  { jd: "ARW", score_jd: 50, state: "AR", score_st: 50 },
  { jd: "ARE", score_jd: 139, state: "AR", score_st: 50 },
  { jd: "TNW", score_jd: 50, state: "TN", score_st: 2 },
  { jd: "TNM", score_jd: 50, state: "TN", score_st: 50 },
  { jd: "NCW", score_jd: 50, state: "NC", score_st: 8 },
  { jd: "NCE", score_jd: 50, state: "NC", score_st: 50 },
  { jd: "SC", score_jd: 74, state: "SC", score_st: 50 },
  { jd: "CAS", score_jd: 85, state: "CA", score_st: 50 },
  { jd: "OKW", score_jd: 96, state: "OK", score_st: 50 },
  { jd: "OKN", score_jd: 70, state: "OK", score_st: 50 },
  { jd: "LAW", score_jd: 50, state: "LA", score_st: 92 },
  { jd: "LAM", score_jd: 50, state: "LA", score_st: 50 },
  { jd: "MSN", score_jd: 50, state: "MS", score_st: 35 },
  { jd: "TNE", score_jd: 50, state: "TN", score_st: 50 },
  { jd: "NCM", score_jd: 50, state: "NC", score_st: 50 },
  { jd: "ALN", score_jd: 47, state: "AL", score_st: 13 },
  { jd: "LAE", score_jd: 36, state: "LA", score_st: 50 },
  { jd: "LAE", score_jd: 50, state: "LA", score_st: 35 },
  { jd: "MSS", score_jd: 25, state: "MS", score_st: 89 },
  { jd: "ALM", score_jd: 50, state: "AL", score_st: 101 },
  { jd: "GAM", score_jd: 50, state: "GA", score_st: 50 },
  { jd: "FLN", score_jd: 97, state: "FL", score_st: 50 },
  { jd: "TXW", score_jd: 50, state: "TX", score_st: 90 },
  { jd: "TXN", score_jd: 75, state: "TX", score_st: 77 },
  { jd: "TXE", score_jd: 86, state: "TX", score_st: 50 },
  { jd: "ALS", score_jd: 50, state: "AL", score_st: 50 },
  { jd: "GAS", score_jd: 50, state: "GA", score_st: 90 },
  { jd: "FLM", score_jd: 50, state: "FL", score_st: 50 },
  { jd: "GU", score_jd: 50, state: "GU", score_st: 47 },
  { jd: "TXS", score_jd: 33, state: "TX", score_st: 50 },
  { jd: "FLS", score_jd: 50, state: "FL", score_st: 50 },
  { jd: "HI", score_jd: 44, state: "HI", score_st: 50 },
  { jd: "AK", score_jd: 50, state: "AK", score_st: 50 },
  { jd: "PR", score_jd: 55, state: "PR", score_st: 126 },
  { jd: "VI", score_jd: 50, state: "VI", score_st: 50 }
];
// [
//     {
//         "state": "CA",
//         "score": 82,
//     },
//     {
//         "state": "OR",
//         "score": 52,
//     },
//     {
//         "state": "WA",
//         "score": 50,
//     },
//     {
//         "state": "ID",
//         "score": 70,
//     },
//     {
//         "state": "AZ",
//         "score": 67,
//     },
//     {
//         "state": "NV",
//         "score": 82,
//     },
//     {
//         "state": "UT",
//         "score": 52,
//     },
//     {
//         "state": "NM",
//         "score": 50,
//     },
//     {
//         "state": "CO",
//         "score": 70,
//     },
//     {
//         "state": "WY",
//         "score": 67,
//     },
//     {
//         "state": "MT",
//         "score": 67,
//     },
//     {
//         "state": "TX",
//         "score": 82,
//     },
//     {
//         "state": "ND",
//         "score": 52,
//     },
//     {
//         "state": "SD",
//         "score": 50,
//     },
//     {
//         "state": "NE",
//         "score": 70,
//     },
//     {
//         "state": "KS",
//         "score": 67,
//     },
//     {
//         "state": "OK",
//         "score": 67,
//     },
//     {
//         "state": "MN",
//         "score": 82,
//     },
//     {
//         "state": "IA",
//         "score": 52,
//     },
//     {
//         "state": "MO",
//         "score": 50,
//     },
//     {
//         "state": "AR",
//         "score": 70,
//     },
//     {
//         "state": "LA",
//         "score": 67,
//     },
//     {
//         "state": "WI",
//         "score": 67,
//     },
//     {
//         "state": "IL",
//         "score": 82,
//     },
//     {
//         "state": "MS",
//         "score": 52,
//     },
//     {
//         "state": "MI",
//         "score": 50,
//     },
//     {
//         "state": "IN",
//         "score": 70,
//     },
//     {
//         "state": "KY",
//         "score": 67,
//     },
//     {
//         "state": "TN",
//         "score": 70,
//     },
//     {
//         "state": "AL",
//         "score": 67,
//     },
//     {
//         "state": "OH",
//         "score": 67,
//     },
//     {
//         "state": "GA",
//         "score": 82,
//     },
//     {
//         "state": "WV",
//         "score": 52,
//     },
//     {
//         "state": "NY",
//         "score": 50,
//     },
//     {
//         "state": "PA",
//         "score": 70,
//     },
//     {
//         "state": "VA",
//         "score": 67,
//     },
//     {
//         "state": "NC",
//         "score": 67,
//     },
//     {
//         "state": "VT",
//         "score": 82,
//     },
//     {
//         "state": "ME",
//         "score": 52,
//     },
//     {
//         "state": "NH",
//         "score": 50,
//     },
//     {
//         "state": "MA",
//         "score": 70,
//     },
//     {
//         "state": "RI",
//         "score": 67,
//     },
//     {
//         "state": "CT",
//         "score": 70,
//     },
//     {
//         "state": "NJ",
//         "score": 67,
//     },
//     {
//         "state": "DE",
//         "score": 67,
//     },
//     {
//         "state": "MD",
//         "score": 82,
//     },
//     {
//         "state": "DC",
//         "score": 52,
//     },
//     {
//         "state": "FL",
//         "score": 50,
//     },
//     {
//         "state": "AK",
//         "score": 52,
//     },
//     {
//         "state": "HI",
//         "score": 52,
//     },
//     {
//         "state": "GU",
//         "score": 67,
//     },
//     {
//         "state": "VI",
//         "score": 67,
//     },
//     {
//         "state": "PR",
//         "score": 67,
//     },
//     ]
export default cartogram_data;
